### PR TITLE
fixed gamemode command

### PR DESCRIPTION
**Pull request by Creeperface01**
- fixed gamemode numbers doesn't work
- fixed  ArrayOutOfBoundsException

### CODE REVIEW

**Comment by iksaku** [comment]
Thanks!

**Comment by Falkirks** [comment]
This should be merged onto `2.0` as well.

**Comment by iksaku** [comment]
Nothing to worry about for now, `2.0.0` is going to be re-written anyways :P

**Comment by Falkirks** [comment]
@iksaku Cool :+1:

**Pull request merged**
