### PR TITLE
Change to getSafeSpawn()

### PR DESCRIPTION
**Pull request by HarveyHans**

### CODE REVIEW

**Comment by Sandertv** [comment]
Is there any reason to merge this?

**Comment by jasonwynn10** [comment]
Nope. getSpawnLocation is much less complicated anyway

**Comment by Sandertv** [comment]
Thought so. It works perfectly finr anyways.

**Comment by HarveyHans** [comment]
@Sandertv This fixes players spawning in mid-air after transferring on a new world.

**Comment by Sandertv** [comment]
It is completely up to you to set the spawn in the air. Some people WANT to have the spawn in the air, so I'm not going to change that. Simply change the world spawn.

**Pull request closed without merging**
