### PR TITLE
CustomAlerts fix

### PR DESCRIPTION
**Pull request by Flavius12**
CustomAlerts fix

### CODE REVIEW

**Comment by LDX-MCPE** [comment]
I already fixed this in an earlier commit. We will add optional messages and customization for them later.

**Comment by Flavius12** [comment]
But there are still some problems with CustomAlerts

**Comment by LDX-MCPE** [comment]
Then send a pull request to @evolsoft.

**Comment by iksaku** [comment]
Just a little problem... Join messages show has "{%0}" instead of player's name xD

**Pull request closed without merging**
