### PR TITLE
Change notify to debug

### PR DESCRIPTION
**Pull request by zKoz210**
I think it better

### CODE REVIEW

**Comment by Sandertv** [comment]
I don't see any reasoning behind changing this.

**Comment by zKoz210** [comment]
Flood in console/logs

**Comment by zKoz210** [comment]
Why server administrators this information?

**Comment by Sandertv** [comment]
Flood? Really? You do realize that this only shows up once everytime a player joins? Unless you have thousands of players joining every minute this shouldn't be of any problem..

**Comment by zKoz210** [comment]
I understand, but this is nonsense. Why display the "Running..." in the console every time? It's pointless, it should only be in debug

**Comment by Sandertv** [comment]
I agree that it's a bit weird, and the message doesn't make sense either. I'll change the message and merge this.

**Pull request merged**
