### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by xpyctum**
hm... strang

### CODE REVIEW

**Comment by Falkirks** [comment]
Thanks for your contribution.

**Comment by PEMapModder** [comment]
Is the code affected?

Users of older versions won't be auto-updated with the change. Note the potential problem.

**Comment by iksaku** [comment]
@PEMapModder Yes, they're auto-updated ;) I have tried with old configs (just for this move) and it worked, Pocketmine does the work

**Comment by PEMapModder** [comment]
No, that's just impossible. PocketMine doesn't know how to merge old data with new templates.

**Pull request merged**
