### PR TITLE
Fix wrong permission node

### PR DESCRIPTION
**Pull request by cloud9350**
default
Check your permission nodes! :+1:

### CODE REVIEW

**Comment by Georggi** [comment]
Wow, @iksaku sometimes makes so many typos:) Thanks @cloud9350

**Comment by iksaku** [comment]
Thanks!

**Comment by LDX-MCPE** [comment]
How long has @Georggi been part of the team?

**Comment by iksaku** [comment]
He has been part of EssentialsPE team forever xD but I added him a few months ago to the repo :P

**Comment by Georggi** [comment]
@LDX-MCPE I'm actually only in have write access to EssentialsPE repo, not to all LegendsOfMCPE repos.

**Comment by cloud9350** [comment]
Deleted my EssentialsPE repository

**Pull request merged**
