### PR TITLE
Update Gamemode.php

### PR DESCRIPTION
**Pull request by Pub4Game**

### CODE REVIEW

**Comment by iksaku** [comment]
It appears that you don't understand the way "Gamemode" command works, you're just adding useless code everywhere, while there are switches for it :P

**Comment by Pub4Game** [comment]
Yeah, I don't understand the change in the command /gamemode...

Why not do as what was /gamemode 1, etc

**Comment by iksaku** [comment]
It has the same functionality as before, and now you could also use "aliases" as "gms" instead of writing "Gamemode survival" ;)

**Comment by Pub4Game** [comment]
I understand... but what about the team /gm and /gamemode? Maybe I'm not comfortable writing the letter or the name of the mode

**Comment by iksaku** [comment]
It's also there xD I strongly recommend you to "try before" ;)

**Comment by Pub4Game** [comment]
image


Thanks)

**Comment by PEMapModder** [comment]
What, `is_int((int) $var)`?

**Pull request closed without merging**
