### PR TITLE
Merging 3.0.0 ALPHA branch, everybody uses this version or above now anyway.

### PR DESCRIPTION
**Pull request by Sandertv**

### CODE REVIEW

**Comment by jrodr10** [comment]
Add support for all of the api's.... why just shitty pmmp

**Comment by SOF3** [comment]
@jrodr10 PMMP API 3.0.0 is still in development all these months. It's not PMMP's fault to have rapidly changing API. It's your own fault to use such indev versions :see_no_evil:

**Comment by Sandertv** [comment]
@jrodr10 if you would read the README, you would clearly see that no support is provided for third party softwares of PMMP. It's not our problem you decide to use a version which EssentialsPE does not work with.

**Comment by SOF3** [comment]
Does EssentialsPE have a spoondetector :see_no_evil:

**Comment by Sandertv** [comment]
Not yet actually, it should.

**Pull request merged**
