### PR TITLE
Fixes #225 and fixes #220

### LINKED ISSUE #220: Placing block problem
When I installed GrabBag, everything is fine, but after i installed esssentialsPe, something happened
.
I cant.place any block, even throwing potion, please help me.

### LINKED ISSUE #225: Placing Block
Hello, I'm search EssentialsPe 1.1.3 php 7. I changed the API and crash, EssentialsPe 2.0.0 is bugged powertool, the placing blocks = Unkown command,sorry for English.

### PR DESCRIPTION
**Pull request by jojoe77777**
Fixes power tool issues (#225 #220)

### CODE REVIEW

**Comment by PEMapModder** [comment]
Why change file mode to 755?

**Comment by jojoe77777** [comment]
Whoops, sorry my computer did that automatically. Fixed.

**Comment by Falkirks** [comment]
Those two commits should really be rebased and squashed before merging.

**Comment by jojoe77777** [comment]
> Those two commits should really be rebased and squashed before merging.

Sorry, not sure how to do that. You mean create a seperate pull request?

**Comment by iksaku** [comment]
@jojoe77777 He means to merge the commits. Do: `git rebase -i`

**Comment by iksaku** [comment]
Closed via `9323d04ca06837bd96bdb23cd84bff73292f05b4`

**Pull request closed without merging**
