### PR TITLE
Made the permission change fix :S

### PR DESCRIPTION
**Pull request by iksaku**
Well, the title says it all, but I need someone to check this and tell me if it *works* so I can oficially implement it xD

### CODE REVIEW

**Comment by LDX-MCPE** [comment]
Everything looks to be in order. :+1:

**Comment by LDX-MCPE** [comment]
I guess I'll have to actually use PurePerms to test it...

**Comment by LDX-MCPE** [comment]
There are some minor issues. The `essentials.kill` node doesn't have achild nodes for self and others, so players by default cannot commit suicide with /kill. The `essentials.ban.exempt` node does not have the parent node `essentials.ban`.

**Comment by iksaku** [comment]
Okey, will check that

**Comment by iksaku** [comment]
I have added a statement that let the player ``siucide`` ny just executing the command, if there is a requested player, its found and the command sender has the permission ``essentials.kill.other`` then the other player will be killed ;)

**Comment by cloud9350** [comment]
If is false, it may require external plugins. (ex - PurePerms)

**Comment by PEMapModder** [comment]
@iksaku you assigned so many people...

**Comment by LDX-MCPE** [comment]
@cloud9350 Not if you're only setting parent nodes to false, which is necessary to utilizing the PocketMine permission system at it's full potential.

**Comment by LDX-MCPE** [comment]
:+1:

**Pull request merged**
