### PR TITLE
API update for 3.0.0-ALPHA9

### PR DESCRIPTION
**Pull request by YTiStrafeNubzHD**
I updated the API Version of the plugin

### CODE REVIEW

**Comment by Sandertv** [comment]
The plugin is still compatible with ALPHA7.

**Comment by YTiStrafeNubzHD** [comment]
Ok. And why Not Alpha 6?

Am 23.11.2017 19:35 schrieb "Sandertv" <notifications@github.com>:

The plugin is still compatible with ALPHA7.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LegendOfMCPE/EssentialsPE/pull/447#issuecomment-346680574>,
or mute the thread

**Comment by Sandertv** [comment]
Because it's not compatible with ALPHA6.

**Comment by YTiStrafeNubzHD** [comment]
How can I see that? I mean I could just add it, cant I?

Am 24.11.2017 12:36 schrieb "Sandertv" <notifications@github.com>:

Because it's not compatible with ALPHA6.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LegendOfMCPE/EssentialsPE/pull/447#issuecomment-346809273>,
or mute the thread

**Comment by Sandertv** [comment]
You could add it and allow users to break their servers with it, yes. If you don't know what effects an API bump do you might want to be careful with it.

**Comment by YTiStrafeNubzHD** [comment]
Could you explain it to me?

Am 24.11.2017 12:45 schrieb "Sandertv" <notifications@github.com>:

You could add it and allow users to break their servers with it, yes. If
you don't know what effects an API bump do you might want to be careful
with it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LegendOfMCPE/EssentialsPE/pull/447#issuecomment-346810750>,
or mute the thread

**Comment by Sandertv** [comment]
If you do not know what consequences doing this has, I recommend not doing so at all. Please refer to the forums to ask whwt the API version is for.

**Comment by YTiStrafeNubzHD** [comment]
I will do so if I want. But of course I will only do that With my own
projects.

And thanks for the hint with the forums

Am 24.11.2017 12:52 schrieb "Sandertv" <notifications@github.com>:

**Pull request closed without merging**
