### PR TITLE
Added autoloading for commands

### PR DESCRIPTION
**Pull request by Falkirks**
This is much smaller and allows for new commands to be added more easily.

### CODE REVIEW

**Comment by Falkirks** [comment]
This branch is getting outdated. I will close this for now, we can pull master back in if we decided this is needed at a later date.

**Comment by iksaku** [comment]
Getting back this idea, currently testing locally ;)

**Comment by PEMapModder** [comment]
Not even @PocketMine uses this method. I think it is not really necessary.

**Comment by PEMapModder** [comment]
Not to merge but bump issue.

**Comment by iksaku** [comment]
Meh... nvm...

**Pull request closed without merging**
