### PR TITLE
Improved isReparable()

### PR DESCRIPTION
**Pull request by luca28pet**

### CODE REVIEW

**Comment by PEMapModder** [comment]
BTW shouldn't it be `isRepairable`?

**Comment by luca28pet** [comment]
Yes, ops

**Comment by iksaku** [comment]
You're removing useful items like "Bow". "Flint&Steel" and "Shears"... Why? D:

**Comment by iksaku** [comment]
Hmmm okey! Now I understand :3 I will merge and commit some changes inspired by it :3 
Thanks!

**Comment by luca28pet** [comment]
@iksaku You're welcome, I love this plugin :+1: :3

**Comment by Falkirks** [comment]
I am going to go ahead and merge this because I want to make changes on top of this.

**Pull request merged**
