### PR TITLE
Fix text issue.

### PR DESCRIPTION
**Pull request by 202831820**

### CODE REVIEW

**Comment by Falkirks** [comment]
Isn't this already fixed in https://github.com/LegendOfMCPE/EssentialsPE/commit/5540f5183239a17cf713a79ea746c137043a6deb

**Comment by 64FF00** [comment]
@Falkirks Ye

**Comment by Georggi** [comment]
@Falkirks It's different line:)

**Comment by Falkirks** [comment]
@Georggi I think your right.

**Comment by Falkirks** [comment]
I will merge this now.

**Pull request merged**
