### PR TITLE
Added updater

### PR DESCRIPTION
**Pull request by PEMapModder**
Not tested

### CODE REVIEW

**Comment by iksaku** [comment]
We're now working on it in the main branch... As always... keep it simple xD

**Comment by PEMapModder** [comment]
It is not simple enough? O.o

**Comment by iksaku** [comment]
Too many classes and code, we only need the *Fetch* and *Install* ones xD

**Comment by PEMapModder** [comment]
Yes, and I only did fetch and install xD

**Comment by abrhamcastillo** [comment]
@iksaku  bro where is the site that i ask question to you like messger in github give me link please

**Comment by Falkirks** [comment]
https://gitter.im/LegendOfMCPE/EssentialsPE

**Pull request closed without merging**
