### PR TITLE
Update KickAll.php

### PR DESCRIPTION
**Pull request by Pub4Game**
Check on the number of players.

### CODE REVIEW

**Comment by Georggi** [comment]
I guess the idea is fine fine, but code wrote awfully and come on, Russians, please, learn English, message should be "There is no players on the server!"...

**Comment by Pub4Game** [comment]
Well it's okay now?

**Comment by Pub4Game** [comment]
Forgive me if I do something wrong :)

**Comment by Georggi** [comment]
Well it seems ok now, @Falkirks should check this though:)

**Comment by PEMapModder** [comment]
Please indent your code properly.

**Comment by LDX-MCPE** [comment]
@PEMapModder, nice job taking over as Grammar Nazi while I was asleep. :+1:

**Comment by Georggi** [comment]
:( Even google translate thinks that it is the same:(

**Comment by Pub4Game** [comment]
@LDX-MCPE you will add this change?

**Pull request closed without merging**
