### PR TITLE
Renaming instead of deleting the bad config

### PR DESCRIPTION
**Pull request by Striker209**
Good if the user wants to keep his data !

### CODE REVIEW

**Comment by PEMapModder** [comment]
Why not like Bukkit, where the old files are changed to `.old` (or whatever, I forgot)?

**Comment by iksaku** [comment]
That's what I was thinking about :P

**Comment by Striker209** [comment]
I created a new pull request

**Comment by PEMapModder** [comment]
#185

**Comment by PEMapModder** [comment]
Fixed in 5004091

**Pull request closed without merging**
