### PR TITLE
Fix error on join (0.16), Fix loads of bugs and errors, and new features

### PR DESCRIPTION
**Pull request by Sandertv**
Find this version at: https://github.com/Sandertv/EssentialsPE
For whoever experiences bugs and problems with this version - Please put the issues in the issues of my fork. It makes it easier for me to be able to close fixed issues.
-  Due to metadata changes some data flags changed. This fixes the errors that occur when a player joins.
-  Implementation of Feed command.
-  Fix for warping other players.
-  Fix the error that has been spamming the console for ages.
-  Fix /vanish command error.

### CODE REVIEW

**Comment by Sandertv** [comment]
The error when using the /vanish command has been fixed now too.

**Comment by NoHaxJustTryHqrd** [comment]
This needs to be merged

**Comment by Pogogo007** [comment]
Fix FNPC I need it xddd

**Comment by Sandertv** [comment]
FNPC is probably still being updated no?

**Comment by Pogogo007** [comment]
Nah the author inactive lol

**Comment by Sandertv** [comment]
Hmmm I'll take a look if I can do something later.

**Comment by Tolo0** [comment]
where can i download your version?

**Comment by Sandertv** [comment]
Here it is: https://github.com/Sandertv/EssentialsPE

**Pull request merged**
